BASE_URL = 'https://beta-admin.fliqzworld.com/api/'
GET_ALL_MESSAGE = 'message'
GET_MESSAGES_BY_USERNAME ='message/@{uid}/details'
SEND_MESSAGE = 'message/{uid}/send-message'






AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2JldGEtYWRtaW4uZmxpcXp3b3JsZC5jb20vYXBpL2xvZ2luIiwiaWF0IjoxNzczNDExMjU2LCJleHAiOjE3NzYwMDMyNTYsIm5iZiI6MTc3MzQxMTI1NiwianRpIjoieVZqTVVPa0xkZWJ1NEhoeCIsInN1YiI6IjE1MiIsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEiLCJzZXRSZWZyZXNoVFRMIjoiNDMyMDAifQ.IT4ZoJw-s-kv1chpTmkNqYvqY8h2SBsbILyql5M9NrY'